#!/bin/bash
##################################################################
# 	            Kubernetes installation			 #
##################################################################

sudo apt-get update && apt-get upgrade -y

##################################################################
#                   Successfully updated                         #
##################################################################



##################################################################
#                      Installing Docker                     	 #
##################################################################

sudo apt install docker.io -y
docker --version
sudo systemctl start docker
sudo systemctl enable docker

##################################################################
#                 Docker installed Successfully 		 # 
##################################################################


sudo swapoff -a
sudo apt-get update && apt-get upgrade -y

###########################################################################################
#	apt-transport-https may be a dummy package; if so, you can skip that package      #
###########################################################################################

sudo apt-get install -y apt-transport-https ca-certificates curl gpg
mkdir -p /etc/apt/keyrings/
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update && apt-get upgrade
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

####### upto her both in master and node #######

curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/calico.yaml -O
kubectl apply -f calico.yaml

ls
sudo apt-get update && apt-get upgrade -y

echo "Kubernetes setup completed successfully."

#####################################################################################
#               copy the kubeadm from the master node and past her                  #
#####################################################################################


